# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
  max_v: 5.0,
  max_a: 2.0
}

waypoints: {
  position: [[0.0,0.0,20.0], [0.0, 100.0, 20.0], [-15.0, 100.0, 20.0], [-15.0, 0.0, 20.0], [-30.0, 0.0, 20.0], [-30.0, 100.0, 20.0], [-45.0, 100.0, 20.0], [-45.0, 0.0, 20.0], [-60.0, 0.0, 20.0], [-60.0, 100.0, 20.0], [-75.0, 100.0, 20.0]], 
  velocity: [[], [], [], [], [], [], [], [], [], []], 
  acceleration: [[], [], [], [], [], [], [], [], [], []]
  # your waypoints here. Think about how to best add any number of waypoints
  # and the according velocity and acceleration constraints.
}

